### ISSUE TITLE
Trackpad Drag and click are not working, Sleep doesn't work

### ISSUE THREAD

**Issue by jogiji** [lunjielee/Opencore-HP-Omen-15-2020#3]
Hi,

I gave your efi a try. 
Things that are not working or I don't know how to resolve:

1 : Trackpad drag windows
2 : Sleep ( if i press sleep it turns off and then on again)

FYI : I have a patched dsdt which works perfectly fine. The only problem there is battery stays at 100%.
https://github.com/jogiji/hp-omen-15-ek0000-hackintosh-efi

Can you help ?

**Comment by lunjielee** [comment]
Hi I pushed the fixes several hours ago for Trackpad drag and click, please check that
As for battery readings I need your original DSDT dump for a SSDT hotpatch, please avoid injecting any modified DSDT file
There are also some sleep fix SSDTs under my ACPI folder please also check those files

**Comment by jogiji** [comment]
Hi @lunjielee here is my dsdt.
I will try your ssdt's infact i am using your ssdt's since past few days.

[DSDT.zip](https://github.com/lunjielee/Opencore-HP-Omen-15-2020/files/5332812/DSDT.zip)

**Comment by jogiji** [comment]
Hi @lunjielee i have used you latest committed efi and i can confirm trackpad works fine now... the only major gripe to this near perfect system is battery drain.. I have applied the gpu ssdt but still no effect..

**Comment by jogiji** [comment]
An update : Battery life seems to be ok now.. after a reboot.. still i am keeping a watch.
